#去申请 https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
wx:
  config:
    appId: ENC(bTxnf/vtyufLHYr/s2D7NIJBKixU5SVOcMxE0uwqTWA=)
    appSecret: ENC(y6r96ALDunwvIR3ROab+HFXOrdppT6HkMTCoxTlgneGv/hIbY4cgphi1uC/AZbXB)
    #模板Id
    templateId: ENC(5kS3Iv51eFZ312jFUl3duQJ7QMAznVxHPVOvxg9hYee+DCiAB5+NbwUOEy31arcN/xYlXngd9HA=)
    openidList:
      - "odx1k6MtHtHscFaOlezu3swC4w6c"#毛毛
#      - "odx1k6FQ_Wyg-iafRmhMIhC1SHQI"#苏苏
#      - "odx1k6JxWib9f35j3TzUdyMNA71s"#胖子
#      - ""

message:
  config:
    birthday1: "7-26" #生日日期
    birthday2: "12-18"
    togetherDate: "2017-03-09" #填你们在一起的那天日期
    message: "Have a happy day and love you"

#去申请 https://tianqiapi.com/user/login
weather:
  config:
    appid: ENC(T6CJaFGI9yIuIe5RGt1PwG4A4WjX1yXX)
    appSecret:  ENC(Mm7RzSB0PRQzER5uxYED88Lx9gCMSQxz)
    city: "深圳"
#注册并购买第二档次，有券，直接白嫖 https://www.apispace.com/eolink/api/myjj/introduction
ApiSpace:
  enableDaily: true #【新增功能】  true：开启每日一句，false：则不开启
  token: ENC(cdmNUxJyxZ6bULDxnzjc4r193RDkP9Mz531xs2zA3RZMrk9F6YiQo7eUdn6Qobww)

jasypt:
  encryptor:
    # 配置加密算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
      prefix: ENC(
      # 算法识别后缀
      suffix: )

server:
  port: 8081

